---
- name: Conduit | Install
  ansible.builtin.import_tasks: install.yml
  when: app_conduit_enabled | default(false) | bool
  tags: ["app_conduit"]

- name: Conduit | Uninstall (hard remove)
  ansible.builtin.import_tasks: uninstall.yml
  when: not (app_conduit_enabled | default(false) | bool)
  tags: ["app_conduit"]
