---
- name: Install baseline packages
  ansible.builtin.apt:
    name: "{{ os_baseline_extra_packages }}"
    state: present
    update_cache: true
  when: os_baseline_extra_packages | length > 0

- name: Upgrade system packages (dist-upgrade)
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
  when: os_baseline_do_upgrade

- name: Autoremove unused packages
  ansible.builtin.apt:
    autoremove: true
  when: os_baseline_autoremove
