---
- name: Snowflake | Install
  ansible.builtin.import_tasks: install.yml
  when: app_snowflake_enabled | default(false) | bool
  tags: ["app_snowflake"]

- name: Snowflake | Uninstall (hard remove)
  ansible.builtin.import_tasks: uninstall.yml
  when: not (app_snowflake_enabled | default(false) | bool)
  tags: ["app_snowflake"]
