---
- name: Tor | Install
  ansible.builtin.import_tasks: install_flow.yml
  when: app_tor_enabled | default(false) | bool
  tags: [app_tor]

- name: Tor | Uninstall (hard remove)
  ansible.builtin.import_tasks: uninstall.yml
  when: not (app_tor_enabled | default(false) | bool)
  tags: [app_tor]
